In [3]:
import pandas as pd

In [2]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.5.0-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\harsh\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in C:\Users\harsh\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ------------- -------------------------- 3.4/9.9 MB 22.1 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 26.1 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 23.4 MB/s  0:00:00
Downloading numpy-2.5.0-cp314-cp314-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ------------------------- -------------- 7.9/12.6 MB 40.3 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 30.2 MB/s  0:00:00
Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed numpy-2.5.0 pandas-3.0.3 tzdata-2026.2
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# Pandas is a Python library used for data analysis, data cleaning, and data manipulation.
import pandas as pd

In [ ]:

import numpy as np

In [8]:
data=np.array([[1,4],[2,5],[4,6]])
data

array([[1, 4],
       [2, 5],
       [4, 6]])

In [29]:
df=pd.DataFrame(data,index=['row1','row2','row3'],columns=['col1','col2'])
df

      col1  col2
row1     1     4
row2     2     5
row3     4     6

In [19]:
data1=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7],[5,6,7,8]])
data1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [25]:
df=pd.DataFrame(data1,index=['row1','row2','row3','row4','row5'],columns=['col1','col2','col3','col4'])
df

      col1  col2  col3  col4
row1     1     2     3     4
row2     2     3     4     5
row3     3     4     5     6
row4     4     5     6     7
row5     5     6     7     8

In [30]:
states=['Maharashtra','Delhi','Punjab','Hariyana']
population=[125000000, 33000000, 30000000, 29000000]

In [35]:
dict_status={'States':states,'Population':population}
dict_status

{'States': ['Maharashtra', 'Delhi', 'Punjab', 'Hariyana'],
 'Population': [125000000, 33000000, 30000000, 29000000]}

In [37]:
India=pd.DataFrame(dict_status)
India

        States  Population
0  Maharashtra   125000000
1        Delhi    33000000
2       Punjab    30000000
3     Hariyana    29000000

In [1]:
import pandas as pd

In [ ]:
# Raw file import into Code using drag and drop 
df=pd.read_csv("D:/python/StudentsPerformance.csv")
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
# Raw file import using direct copy path
df1=pd.read_csv("https://raw.githubusercontent.com/Harshita-official/Python-for-Data-Science/refs/heads/main/python-for-data-science-main/02.Intro%20to%20Pandas/StudentsPerformance.csv")
df1

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [6]:
import requests
import pandas as pd
from io import StringIO
from bs4 import BeautifulSoup

In [4]:
!pip install requests beautifulsoup4 lxml

Collecting requests
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.15.0-py3-none-any.whl.metadata (3.8 kB)
Collecting lxml
  Downloading lxml-6.1.1-cp314-cp314-win_amd64.whl.metadata (3.6 kB)
Collecting charset_normalizer<4,>=2 (from requests)
  Downloading charset_normalizer-3.4.8-cp314-cp314-win_amd64.whl.metadata (42 kB)
Collecting idna<4,>=2.5 (from requests)
  Downloading idna-3.18-py3-none-any.whl.metadata (6.1 kB)
Collecting urllib3<3,>=1.26 (from requests)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests)
  Downloading certifi-2026.6.17-py3-none-any.whl.metadata (2.5 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4)
  Downloading soupsieve-2.8.4-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in C:\Users\harsh\AppData\Roaming\Python\Python314\site-packages (from beautifulsoup4) (4.15.0)
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
Downloading charset_normalizer-3.4.8-cp314-cp314-win_amd64.whl (162 kB)
Downloading idna-3.18-py3-none-any.whl (65 kB)
Downloading urllib3-2.7.0-py3-none-any.whl (131 kB)
Downloading beautifulsoup4-4.15.0-py3-none-any.whl (109 kB)
Downloading lxml-6.1.1-cp314-cp314-win_amd64.whl (4.1 MB)
   ---------------------------------------- 0.0/4.1 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.1 MB 2.8 MB/s eta 0:00:02
   ---------- ----------------------------- 1.0/4.1 MB 3.0 MB/s eta 0:00:02
   ------------------ --------------------- 1.8/4.1 MB 3.0 MB/s eta 0:00:01
   ------------------------- -------------- 2.6/4.1 MB 3.1 MB/s eta 0:00:01
   ------------------------------ --------- 3.1/4.1 MB 3.1 MB/s eta 0:00:01
   -------------------------------------- - 3.9/4.1 MB 3.1 MB/s eta 0:00:01
   ---------------------------------------- 4.1/4.1 MB 3.1 MB/s  0:00:01
Downloading certifi-2026.6.17-py3-none-any.whl (133 kB)
Downloading soupsieve-2.8.4-py3-none-any.whl (37 kB)
Installing collected packages: urllib3, soupsieve, lxml, idna, charset_normalizer, certifi, requests, beautifulsoup4

   ---------------------------------------- 0/8 [urllib3]
   ---------------------------------------- 0/8 [urllib3]
   ---------------------------------------- 0/8 [urllib3]
   ---------------------------------------- 0/8 [urllib3]
   ---------------------------------------- 0/8 [urllib3]
   ---------------------------------------- 0/8 [urllib3]
   ----- ---------------------------------- 1/8 [soupsieve]
   ----- ---------------------------------- 1/8 [soupsieve]
   ---------- ----------------------------- 2/8 [lxml]
   ---------- ----------------------------- 2/8 [lxml]
   ---------- ----------------------------- 2/8 [lxml]
   ---------- ----------------------------- 2/8 [lxml]
   ---------- ----------------------------- 2/8 [lxml]
   ---------- ----------------------------- 2/8 [lxml]
   ---------- ----------------------------- 2/8 [lxml]
   --------------- ------------------------ 3/8 [idna]
   --------------- ------------------------ 3/8 [idna]
   --------------- ------------------------ 3/8 [idna]
   -------------------- ------------------- 4/8 [charset_normalizer]
   -------------------- ------------------- 4/8 [charset_normalizer]
   -------------------- ------------------- 4/8 [charset_normalizer]
   ------------------------------ --------- 6/8 [requests]
   ------------------------------ --------- 6/8 [requests]
   ------------------------------ --------- 6/8 [requests]
   ------------------------------ --------- 6/8 [requests]
   ----------------------------------- ---- 7/8 [beautifulsoup4]
   ----------------------------------- ---- 7/8 [beautifulsoup4]
   ----------------------------------- ---- 7/8 [beautifulsoup4]
   ---------------------------------------- 8/8 [beautifulsoup4]

Successfully installed beautifulsoup4-4.15.0 certifi-2026.6.17 charset_normalizer-3.4.8 idna-3.18 lxml-6.1.1 requests-2.34.2 soupsieve-2.8.4 urllib3-2.7.0

In [ ]:
url = "https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue"

headers = {
    "User-Agent": "MyDataAnalysisBot/1.0 (your_email@example.com)"
}

response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, 'html.parser')

# Step 1: Use find_all to get a list of all matching tables
all_tables = soup.find_all('table', class_='wikitable sortable')
# Step 2: Create a list to store your DataFrames
dfs = []
# Step 3: Loop through each table found for table in all_tables:
for table in all_tables:
# Use StringIO to wrap the string version of the table
    df = pd.read_html(StringIO(str(table)))[0]
    dfs.append(df)

df = pd.read_html(StringIO(str(table)))[0]

pd.set_option('display.max_rows', 100)

print(df)
# https://en.wikipedia.org/wiki/List_of_largest_companies_in_Indi/a

   Rank                Name                        Industry  \
0     1            Alphabet  Technology and cloud computing
1     2               Apple                      Technology
2     3  Berkshire Hathaway                    Conglomerate
3     4           Microsoft  Technology and cloud computing
4     5              Nvidia                      Technology
5     6      Meta Platforms                      Technology
6     7              Amazon      Retail and cloud computing
7     8      JPMorgan Chase                      Financials
8     9          ExxonMobil              Petroleum industry
9    10     Bank of America                      Financials

   Profits (USD millions)               Headquarters
0                  100118  Mountain View, California
1                   93736      Cupertino, California
2                   88995            Omaha, Nebraska
3                   88136        Redmond, Washington
4                   72880    Santa Clara, California
5                   62360     Menlo Park, California
6                   59248        Seattle, Washington
7                   58471    New York City, New York
8                   33680              Spring, Texas
9                   27132  Charlotte, North Carolina

In [13]:
dfs[0]

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,680985,5.1%,2100000,"Bentonville, Arkansas"
1,2,Amazon,Retail and cloud computing,637959,11.0%,1556000,"Seattle, Washington"
2,3,UnitedHealth Group,Healthcare,400278,7.7%,400000,"Minnetonka, Minnesota"
3,4,Apple,Technology,391035,2.0%,164000,"Cupertino, California"
4,5,CVS Health,Healthcare,372809,4.2%,259500,"Woonsocket, Rhode Island"
5,6,Berkshire Hathaway,Conglomerate,371433,1.9%,392400,"Omaha, Nebraska"
6,7,Alphabet,Technology and cloud computing,350018,13.9%,183323,"Mountain View, California"
7,8,Exxon Mobil,Petroleum,349595,1.5%,60900,"Spring, Texas"
8,9,McKesson Corporation,Healthcare,308951,11.7%,48000,"Irving, Texas"
9,10,Cencora,Pharmacy wholesale,293959,12.1%,44000,"Conshohocken, Pennsylvania"
10,11,JPMorgan Chase,Financials,278906,16.5%,317233,"New York City, New York"
11,12,Costco Wholesale,Retail,254453,5.0%,333000,"Issaquah, Washington"
12,13,Cigna,Health insurance,247121,26.6%,72398,"Bloomfield, Connecticut"
13,14,Microsoft,Technology and cloud computing,245122,15.7%,228000,"Redmond, Washington"
14,15,Cardinal Health,Healthcare,226827,10.6%,48411,"Dublin, Ohio"
15,16,Chevron,Petroleum,202792,0.9%,45298,"Houston, Texas"
16,17,Bank of America,Financials,192434,11.9%,213193,"Charlotte, North Carolina"
17,18,General Motors,Automotive,187442,9.1%,162000,"Detroit, Michigan"
18,19,Ford Motor,Automotive,184992,5.0%,171000,"Dearborn, Michigan"
19,20,Elevance Health,Healthcare,177011,3.3%,103679,"Indianapolis, Indiana"
20,21,Citigroup,Financials,170757,8.9%,227855,"New York City, New York"
21,22,Meta Platforms,Technology,164501,21.9%,74067,"Menlo Park, California"
22,23,Centene,Healthcare,163071,5.9%,60500,"St. Louis, Missouri"
23,24,The Home Depot,Retail,159514,4.5%,470100,"Atlanta, Georgia"
24,25,Fannie Mae,Financials,152670,8.1%,8200,"Washington, D.C."
25,26,Walgreens Boots Alliance,Pharmaceutical,147658,6.2%,252500,"Deerfield, Illinois"
26,27,Kroger,Retail,147123,-1.9%,409000,"Cincinnati, Ohio"
27,28,Phillips 66,Petroleum,145496,-2.9%,13200,"Houston, Texas"
28,29,Marathon Petroleum,Petroleum,140412,-6.6%,18300,"Findlay, Ohio"
29,30,Verizon Communications,Telecommunications,134788,0.6%,99600,"New York City, New York"
30,31,Nvidia,Technology,130497,114.2%,36000,"Santa Clara, California"
31,32,Goldman Sachs Group,Financials,126853,17.0%,46500,"New York City, New York"
32,33,Wells Fargo,Financials,125397,8.7%,217502,"San Francisco, California"
33,34,Valero Energy,Petroleum,123974,-10.8%,9910,"San Antonio, Texas"
34,35,Comcast,Telecommunications,123731,1.8%,182000,"Philadelphia, Pennsylvania"
35,36,State Farm Insurance,Financials,122951,18.0%,67381,"Bloomington, Illinois"
36,37,AT&T,Conglomerate and telecommunications,122336,-0.1%,140990,"Dallas, Texas"
37,38,Freddie Mac,Financials,122052,13.0%,8090,"McLean, Virginia"
38,39,Humana,Health insurance,117761,10.7%,65680,"Louisville, Kentucky"
39,40,Morgan Stanley,Financials,107285,11.5%,80478,"New York City, New York"
40,41,Target,Retail,106566,-0.8%,440000,"Minneapolis, Minnesota"
41,42,StoneX Group,Financials,99888,64.1%,4500,"New York City, New York"
42,43,Tesla,Automotive and energy,97690,0.9%,125665,"Austin, Texas"
43,44,Dell Technologies,Technology,95567,8.1%,108000,"Round Rock, Texas"
44,45,PepsiCo,Beverage,91854,0.4%,319000,"Purchase, New York"
45,46,Walt Disney,Media,91361,2.8%,205040,"Burbank, California"
46,47,United Parcel Service,Transportation,91070,0.1%,372180,"Atlanta, Georgia"
47,48,Johnson & Johnson,Pharmaceutical,88821,-6.7%,138100,"New Brunswick, New Jersey"
48,49,FedEx,Transportation,87693,-2.7%,422100,"Memphis, Tennessee"
49,50,Archer Daniels Midland,Food industry,85530,-8.9%,43213,"Chicago, Illinois"
50,51,Procter & Gamble,Consumer products manufacturing,84039,2.5%,108000,"Cincinnati, Ohio"
51,52,Lowe's,Retail,83674,-3.1%,215500,"Mooresville, North Carolina"
52,53,Energy Transfer Partners,Petroleum,82671,5.2%,16248,"Dallas, Texas"
53,54,RTX,Aerospace and defense,80739,17.1%,186000,"Arlington County, Virginia"
54,55,Albertsons,Retail,79238,2.0%,196650,"Boise, Idaho"
55,56,Sysco,Food processing,78844,3.3%,76000,"Houston, Texas"
56,57,Progressive,Insurance,75372,21.4%,66308,"Mayfield Village, Ohio"
57,58,American Express,Financials,74201,10.1%,75100,"New York City, New York"
58,59,Lockheed Martin,Aerospace and defense,71043,5.1%,121000,"Bethesda, Maryland"
59,60,MetLife,Financials,70986,6.1%,45000,"New York City, New York"
60,61,HCA Healthcare,Healthcare,70603,8.7%,271000,"Nashville, Tennessee"
61,62,Prudential Financial,Financials,70405,30.4%,37936,"Newark, New Jersey"
62,63,Boeing,Aerospace and defense,66517,-14.5%,172000,"Arlington County, Virginia"
63,64,Caterpillar,Machinery,64809,-3.4%,112900,"Irving, Texas"
64,65,Merck,Pharmaceutical industry,64168,6.7%,74000,"Kenilworth, New Jersey"
65,66,Allstate,Insurance,64106,12.3%,55200,"Northfield Township, Illinois"
66,67,Pfizer,Pharmaceutical industry,63627,8.8%,81000,"New York City, New York"
67,68,IBM,Technology and cloud computing,62753,1.4%,284500,"Armonk, New York"
68,69,New York Life Insurance Company,Insurance,62639,15.3%,15131,"New York City, New York"
69,70,Delta Air Lines,Airline,61643,6.2%,103000,"Atlanta, Georgia"
70,71,Publix Super Markets,Retail,60177,4.6%,255000,"Lakeland, Florida"
71,72,Nationwide Mutual Insurance Company,Financials,58646,7.4%,22453,"Columbus, Ohio"
72,73,TD Synnex,Information Technology,58452,1.6%,25750,"Clearwater, Florida"
73,74,United Airlines Holdings,Airline,57063,6.2%,107300,"Chicago, Illinois"
74,75,ConocoPhillips,Petroleum,56953,-2.8%,11800,"Houston, Texas"
75,76,TJX,Retail,56360,4.0%,364000,"Framingham, Massachusetts"
76,77,AbbVie,Pharmaceutical,56334,3.7%,55000,"Lake Bluff, Illinois"
77,78,Enterprise Products Partners,Petroleum,56219,13.1%,7800,"Houston, Texas"
78,79,Charter Communications,Telecommunications,55085,0.9%,94500,"Stamford, Connecticut"
79,80,Performance Food Group,Food processing,54681,2.5%,36815,"Richmond, Virginia"
80,81,American Airlines Group,Airline,54211,2.7%,133300,"Fort Worth, Texas"
81,82,Capital One Financial,Financials,53938,9.0%,52600,"Tysons, Virginia"
82,83,Cisco Systems,Telecom hardware manufacturing,53803,-5.6%,90400,"San Jose, California"
83,84,HP,Technology,53559,-0.3%,58000,"Palo Alto, California"
84,85,Tyson Foods,Food processing,53309,0.8%,138000,"Springdale, Arkansas"
85,86,Intel,Technology,53101,-2.1%,108900,"Santa Clara, California"
86,87,Oracle,Technology,52961,6.0%,159000,"Austin, Texas"
87,88,Broadcom,Technology,52432,46.4%,37000,"Palo Alto, California"
88,89,Deere,Agriculture manufacturing,51716,-15.6%,55524,"Moline, Illinois"
89,90,Nike,Apparel,51361,0.3%,78400,"Beaverton, Oregon"
90,91,Liberty Mutual Insurance Group,Insurance,50429,-4.1%,40000,"Boston, Massachusetts"
91,92,Plains GP Holdings,Petroleum,50073,2.8%,4200,"Houston, Texas"
92,93,USAA,Insurance,48560,14.3%,38018,"San Antonio, Texas"
93,94,Bristol-Myers Squibb,Pharmaceutical,48300,7.3%,34100,"New York City, New York"
94,95,Ingram Micro Holding,Technology,47984,-0.1%,26125,"Irvine, California"
95,96,General Dynamics,Aerospace and defense,47716,12.9%,117000,"Reston, Virginia"
96,97,Coca-Cola,Beverage,47061,2.9%,69700,"Atlanta, Georgia"
97,98,TIAA,Financials,46946,2.6%,15623,"New York City, New York"
98,99,Travelers,Insurance,46423,12.2%,34000,"New York City, New York"
99,100,Eli Lilly,Pharmaceutical,45043,32.0%,47000,"Indianapolis, Indiana"

In [15]:
dfs[1]

,Rank,Name,Industry,Revenue (USD billions),Employees,Headquarters
0,1,Cargill,Food & Drink,154.00,155000,"Minnetonka, Minnesota"
1,2,Koch,Multicompany,125.00,120000,"Wichita, Kansas"
2,3,Publix Super Markets,Food Markets,59.70,260000,"Lakeland, Florida"
3,4,Mars,Food & Drink,55.00,150000,"McLean, Virginia"
4,5,H-E-B Grocery Company,Food Markets,49.57,175000,"San Antonio, Texas"
5,6,Reyes Holdings,"Food, Drink & Tobacco",44.00,36000,"Rosemont, Illinois"
6,7,Enterprise Mobility,Services,38.00,100000,"Clayton, Missouri"
7,8,Fidelity Investments,Insurance,32.70,78000,"Boston, Massachusetts"
8,9,Southern Glazer's Wine & Spirits,"Food, Drink & Tobacco",25.00,24000,"Miramar, Florida"
9,10,Cox Enterprises,Media,23.50,50000,"Atlanta, Georgia"

In [16]:
dfs[2]

,Rank,Name,Industry,Profits (USD millions),Headquarters
0,1,Alphabet,Technology and cloud computing,100118,"Mountain View, California"
1,2,Apple,Technology,93736,"Cupertino, California"
2,3,Berkshire Hathaway,Conglomerate,88995,"Omaha, Nebraska"
3,4,Microsoft,Technology and cloud computing,88136,"Redmond, Washington"
4,5,Nvidia,Technology,72880,"Santa Clara, California"
5,6,Meta Platforms,Technology,62360,"Menlo Park, California"
6,7,Amazon,Retail and cloud computing,59248,"Seattle, Washington"
7,8,JPMorgan Chase,Financials,58471,"New York City, New York"
8,9,ExxonMobil,Petroleum industry,33680,"Spring, Texas"
9,10,Bank of America,Financials,27132,"Charlotte, North Carolina"

In [17]:
url = "https://en.wikipedia.org/wiki/List_of_largest_companies_in_India"

headers = {
    "User-Agent": "MyDataAnalysisBot/1.0 (your_email@example.com)"
}

response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, 'html.parser')

# Step 1: Use find_all to get a list of all matching tables
all_tables = soup.find_all('table', class_='wikitable sortable')
# Step 2: Create a list to store your DataFrames
dfs = []
# Step 3: Loop through each table found for table in all_tables:
for table in all_tables:
# Use StringIO to wrap the string version of the table
    df = pd.read_html(StringIO(str(table)))[0]
    dfs.append(df)

df = pd.read_html(StringIO(str(table)))[0]

pd.set_option('display.max_rows', 100)

print(df)

    Rank                             Name            Industry  \
0      1      Reliance Industries Limited        Conglomerate
1      2       Life Insurance Corporation           Insurance
2      3           Indian Oil Corporation         Oil and gas
3      4              State Bank of India             Banking
4      5  Oil and Natural Gas Corporation         Oil and gas
5      6                        HDFC Bank             Banking
6      7                      Tata Motors          Automotive
7      8                 Bharat Petroleum         Oil and gas
8      9                       ICICI Bank             Banking
9     10                  Larsen & Toubro       Capital goods
10    11        Tata Consultancy Services            Infotech
11    12              Hindalco Industries   Metals and mining
12    13                       Tata Steel      Iron and steel
13    14                     NTPC Limited           Utilities
14    15                    Bharti Airtel  Telecommunications
15    16                    JSW Steel Ltd      Iron and steel
16    17                          Infosys            Infotech
17    18              Mahindra & Mahindra          Automotive
18    19                Vedanta Resources   Metals and mining
19    20              Maruti Suzuki India          Automotive
20    21                        Axis Bank             Banking
21    22                       Coal India   Metals and mining
22    23                   Bank of Baroda             Banking
23    24                      Canara Bank             Banking
24    25                Grasim Industries         Diversified
25    26                             GAIL         Oil and gas
26    27             Punjab National Bank             Banking
27    28                    Bajaj Finserv          Financials
28    29                    Nayara Energy         Oil and gas
29    30              Union Bank of India             Banking
30    31                 HCL Technologies            Infotech
31    32           Motherson Sumi Systems          Automotive
32    33        Power Finance Corporation  Financial services
33    34              Kotak Mahindra Bank             Banking
34    35         Steel Authority of India      Iron and steel
35    36                      ITC Limited      Consumer goods
36    37                            Wipro            Infotech
37    38                         Flipkart          E-commerce
38    39                           IndiGo             Airline
39    40                    Bank of India             Banking
40    41                      Indian Bank             Banking
41    42              Hyundai Motor India          Automotive
42    43                       Tata Power           Utilities
43    44                    Titan Company  Gems and jewellery
44    45           Toyota Kirloskar Motor          Automotive
45    46               Hindustan Unilever      Consumer goods
46    47                Adani Enterprises             Trading
47    48                AWL Agri Business      Consumer goods
48    49                Avenue Supermarts              Retail
49    50                           NABARD             Finance

    Revenue (in ₹ crore) Revenue growth Profits (in ₹ crore) Headquarters  \
0                 997795             8%                69648       Mumbai
1                 893465             4%                48320       Mumbai
2                 766008             2%                13598    New Delhi
3                 663343            12%                77561       Mumbai
4                 624805             0%                36226    New Delhi
5                 470916            15%                70792       Mumbai
6                 449357             2%                27830       Mumbai
7                 443948             2%                13337       Mumbai
8                 294587            25%                51029       Mumbai
9                 260745            16%                15037       Mumbai
10                259286             6%                48553       Mumbai
11                243534            13%                16001       Mumbai
12                220507             3%                 3421       Mumbai
13                196847             7%                23422    New Delhi
14                194387            26%                33556    New Delhi
15                168689             6%                26713       Mumbai
16                166590             6%                28165    Bangalore
17                162941            13%                12929       Mumbai
18                160450             7%                14988   London, UK
19                159407             8%                14500    New Delhi
20                155917            13%                28055       Mumbai
21                155605             1%                35358      Kolkata
22                152884             8%                20716     Vadodara
23                152658            10%                17540    Bangalore
24                151048            14%                 3706       Mumbai
25                147417             8%                12450    New Delhi
26                141570            15%                18480    New Delhi
27                133840            21%                 8872         Pune
28                130326             3%                 6080       Mumbai
29                129979            10%                18027       Mumbai
30                119488             7%                17390        Noida
31                114502            16%                 3803        Noida
32                107203            17%                22991    New Delhi
33                107095            14%                22126       Mumbai
34                103861             6%                 2372    New Delhi
35                 93705            31%                34747      Kolkata
36                 92937             1%                13135    Bangalore
37                 84230            18%               −5,189    Bangalore
38                 84098            18%                 7258      Gurgaon
39                 80625            19%                 9548       Mumbai
40                 72051            12%                11261      Chennai
41                 70282             2%                 5640      Gurgaon
42                 68892             6%                 3971       Mumbai
43                 68758            27%                 3337    Bangalore
44                 65958            16%                 5672       Bidadi
45                 64891             3%                10649       Mumbai
46                 62652            12%                 7112    Ahmedabad
47                 61387            24%                 1226    Ahmedabad
48                 60599            17%                 2708       Mumbai
49                 59292            20%                 7803       Mumbai

   State controlled
0               NaN
1               Yes
2               Yes
3               Yes
4               Yes
5               NaN
6               NaN
7               Yes
8               NaN
9               NaN
10              NaN
11              NaN
12              NaN
13              Yes
14              NaN
15              NaN
16              NaN
17              NaN
18              NaN
19              NaN
20              Yes
21              Yes
22              Yes
23              Yes
24              NaN
25              Yes
26              Yes
27              NaN
28              NaN
29              Yes
30              NaN
31              NaN
32              Yes
33              NaN
34              Yes
35              NaN
36              NaN
37              NaN
38              NaN
39              Yes
40              Yes
41              NaN
42              NaN
43              NaN
44              NaN
45              NaN
46              NaN
47              NaN
48              NaN
49              Yes

In [18]:
dfs[0]

,Rank,Forbes 2000 rank,Name,Headquarters,Revenue (billions US$),Profit (billions US$),Assets (billions US$),Value (billions US$),Industry
0,1,49,Reliance Industries Limited,Mumbai,108.8,8.4,210.5,233.1,Conglomerate
1,2,55,State Bank of India,Mumbai,71.8,8.1,807.4,87.6,Banking
2,3,65,HDFC Bank,Mumbai,49.3,7.7,483.2,133.6,Banking
3,4,70,Life Insurance Corporation,New Delhi,98.0,4.9,561.4,73.6,Insurance
4,5,142,ICICI Bank,Mumbai,28.5,5.3,283.5,95.3,Banking
5,6,207,Oil and Natural Gas Corporation,New Delhi,77.5,5.1,80.6,41.9,Oil and gas
6,7,259,Indian Oil Corporation,New Delhi,93.8,5.0,57.8,27.8,Oil and gas
7,8,284,Tata Motors,Mumbai,52.9,3.8,44.4,43.8,Automotive
8,9,293,Axis Bank,Mumbai,16.7,3.2,182.0,42.3,Banking
9,10,372,NTPC Limited,New Delhi,21.2,2.4,54.7,42.5,Utilities
10,11,398,Larsen & Toubro,Mumbai,26.7,1.6,40.7,56.9,Capital goods
11,12,412,Tata Consultancy Services,Mumbai,29.1,5.5,17.6,166.5,Infotech
12,13,440,Bank of Baroda,Vadodara,17.1,2.3,198.4,16.2,Banking
13,14,442,Kotak Mahindra Bank,Mumbai,11.4,2.2,92.0,40.5,Banking
14,15,472,Bharti Airtel,New Delhi,18.1,0.9,53.3,91.5,Telecommunication
15,16,488,Coal India,Kolkata,17.2,3.9,28.5,34.8,Metals and mining
16,17,525,Canara Bank,Bangalore,16.8,1.8,184.0,12.4,Banking
17,18,533,Power Finance Corporation,New Delhi,11.1,2.4,124.6,18.5,Financials
18,19,537,Bharat Petroleum,Mumbai,54.1,3.2,24.3,16.4,Oil and gas
19,20,569,Infosys,Bangalore,18.6,3.2,16.5,71.9,Infotech
20,21,571,Punjab National Bank,New Delhi,14.8,1.1,191.7,16.5,Banking
21,22,575,Union Bank of India,Mumbai,14.3,1.7,168.1,12.7,Banking
22,23,592,Bajaj Finserv,Pune,13.0,1.0,64.5,30.3,Financials
23,24,593,Mahindra & Mahindra,Mumbai,16.8,1.4,28.3,37.5,Automotive
24,25,645,JSW Steel Ltd,Mumbai,21.1,1.1,27.4,26.6,Iron and steel
25,26,684,Hindalco Industries,Mumbai,26.1,1.1,27.1,17.7,Metals and mining
26,27,746,Grasim Industries,Mumbai,15.3,0.7,47.0,19.8,Diversified
27,28,764,HCL Technologies,Noida,13.3,1.9,12.0,43.4,Infotech
28,29,810,ITC Limited,Kolkata,8.5,2.5,10.5,65.4,Consumer goods
29,30,827,Power Grid Corporation of India,Gurgaon,5.6,1.9,29.6,35.0,Utilities
30,31,834,Tata Steel,Kolkata,28.3,−0.4,32.7,25.1,Iron and steel
31,32,901,IndusInd Bank,Mumbai,6.7,1.1,61.8,13.2,Banking
32,33,922,Indian Railway Finance Corporation,New Delhi,3.2,0.7,58.6,26.5,Financials
33,34,926,Wipro,Bangalore,10.8,1.3,13.8,28.9,Infotech
34,35,930,GAIL,New Delhi,16.1,1.2,15.0,16.1,Oil and gas
35,36,947,Indian Bank,Chennai,7.8,1.0,95.4,8.7,Banking
36,37,961,Vedanta Limited,Mumbai,17.4,0.5,22.9,19.7,Metals and mining
37,38,1048,Adani Power,Ahmedabad,6.1,2.5,11.1,29.4,Energy
38,39,1053,Bank of India,Mumbai,8.1,0.8,110.8,6.7,Banking
39,40,1059,Adani Enterprises,Ahmedabad,12.7,0.4,19.3,41.9,Holding
40,41,1161,Sun Pharmaceutical,Mumbai,5.7,1.1,9.6,44.1,Pharmaceuticals
41,42,1212,IndiGo,Gurgaon,7.9,0.9,8.8,20.2,Airline
42,43,1219,Adani Ports & SEZ,Ahmedabad,3.2,1.0,14.3,34.6,Shipping
43,44,1259,IDBI Bank,Mumbai,3.7,0.7,43.7,10.9,Banking
44,45,1264,Bajaj Auto,Pune,5.4,0.9,4.7,29.4,Automotive
45,46,1281,Shriram Transport Finance,Chennai,4.4,0.9,29.8,10.7,Financials
46,47,1384,Asian Paints,Mumbai,4.3,0.7,3.6,32.3,Chemicals
47,48,1534,Tata Power,Mumbai,7.4,0.5,16.7,16.7,Utilities
48,49,1562,Titan Company,Bangalore,6.2,0.0,2.3,1.1,Gems and jewellery
49,50,1604,Jio Financial Services,Mumbai,0.2,0.2,17.4,27.2,Financials
50,49,1568,Rajesh Exports,Bangalore,32.6,0.1,4.1,2.0,Gems and jewellery
51,50,1617,DMart,Mumbai,6.1,0.3,2.5,36.6,Retail
52,51,1693,Jindal Steel and Power,New Delhi,6.0,0.6,9.4,12.4,Iron and steel
53,52,1697,LIC Housing Finance,Mumbai,3.3,0.4,34.9,4.3,Financials
54,53,1699,Adani Green Energy,Ahmedabad,1.1,0.1,10.6,34.8,Renewable energy
55,54,1704,Bajaj Holdings & Investment,Mumbai,0.2,0.9,7.8,11.0,Holding
56,55,1760,General Insurance Corporation,Mumbai,5.7,0.9,20.9,7.2,Insurance
57,56,1769,Yes Bank,Mumbai,4.0,0.2,48.7,8.3,Banking
58,57,1805,Motherson Sumi Systems,Noida,11.4,0.2,9.4,10.5,Automotive
59,58,1821,Bharat Electronics,Bangalore,2.2,0.4,4.4,21.8,Aerospace and defense
60,59,1840,Central Bank of India,Mumbai,4.3,0.3,53.7,6.4,Banking
61,60,1842,Bank of Maharashtra,Pune,2.8,0.5,36.8,5.5,Banking
62,61,1848,Indus Towers,Gurgaon,3.5,0.7,6.7,11.1,Telecommunication
63,62,1853,Steel Authority of India,New Delhi,12.9,0.4,15.6,8.3,Iron and steel
64,63,1869,Federal Bank,Kochi,3.2,0.5,38.1,4.8,Banking
65,64,1873,DLF,Gurgaon,0.8,0.3,7.2,25.2,Real estate
66,65,1895,Dr. Reddy's Laboratories,Hyderabad,3.4,0.7,4.6,11.6,Pharmaceuticals
67,66,1908,Varun Beverages,Gurgaon,2.0,0.3,1.8,23.6,Beverages
68,67,1949,CIFCL,Chennai,2.3,0.4,18.8,13.0,Financials
69,68,1957,NMDC,Hyderabad,2.5,0.8,3.9,9.7,Mining
70,69,1980,ABB India,Bangalore,1.3,0.2,1.3,21.3,Capital goods

In [19]:
dfs[1]

,Rank,Name,Industry,Revenue (in ₹ crore),Revenue growth,Profits (in ₹ crore),Headquarters,State controlled
0,1,Reliance Industries Limited,Conglomerate,997795,8%,69648,Mumbai,NaN
1,2,Life Insurance Corporation,Insurance,893465,4%,48320,Mumbai,Yes
2,3,Indian Oil Corporation,Oil and gas,766008,2%,13598,New Delhi,Yes
3,4,State Bank of India,Banking,663343,12%,77561,Mumbai,Yes
4,5,Oil and Natural Gas Corporation,Oil and gas,624805,0%,36226,New Delhi,Yes
5,6,HDFC Bank,Banking,470916,15%,70792,Mumbai,NaN
6,7,Tata Motors,Automotive,449357,2%,27830,Mumbai,NaN
7,8,Bharat Petroleum,Oil and gas,443948,2%,13337,Mumbai,Yes
8,9,ICICI Bank,Banking,294587,25%,51029,Mumbai,NaN
9,10,Larsen & Toubro,Capital goods,260745,16%,15037,Mumbai,NaN
10,11,Tata Consultancy Services,Infotech,259286,6%,48553,Mumbai,NaN
11,12,Hindalco Industries,Metals and mining,243534,13%,16001,Mumbai,NaN
12,13,Tata Steel,Iron and steel,220507,3%,3421,Mumbai,NaN
13,14,NTPC Limited,Utilities,196847,7%,23422,New Delhi,Yes
14,15,Bharti Airtel,Telecommunications,194387,26%,33556,New Delhi,NaN
15,16,JSW Steel Ltd,Iron and steel,168689,6%,26713,Mumbai,NaN
16,17,Infosys,Infotech,166590,6%,28165,Bangalore,NaN
17,18,Mahindra & Mahindra,Automotive,162941,13%,12929,Mumbai,NaN
18,19,Vedanta Resources,Metals and mining,160450,7%,14988,"London, UK",NaN
19,20,Maruti Suzuki India,Automotive,159407,8%,14500,New Delhi,NaN
20,21,Axis Bank,Banking,155917,13%,28055,Mumbai,Yes
21,22,Coal India,Metals and mining,155605,1%,35358,Kolkata,Yes
22,23,Bank of Baroda,Banking,152884,8%,20716,Vadodara,Yes
23,24,Canara Bank,Banking,152658,10%,17540,Bangalore,Yes
24,25,Grasim Industries,Diversified,151048,14%,3706,Mumbai,NaN
25,26,GAIL,Oil and gas,147417,8%,12450,New Delhi,Yes
26,27,Punjab National Bank,Banking,141570,15%,18480,New Delhi,Yes
27,28,Bajaj Finserv,Financials,133840,21%,8872,Pune,NaN
28,29,Nayara Energy,Oil and gas,130326,3%,6080,Mumbai,NaN
29,30,Union Bank of India,Banking,129979,10%,18027,Mumbai,Yes
30,31,HCL Technologies,Infotech,119488,7%,17390,Noida,NaN
31,32,Motherson Sumi Systems,Automotive,114502,16%,3803,Noida,NaN
32,33,Power Finance Corporation,Financial services,107203,17%,22991,New Delhi,Yes
33,34,Kotak Mahindra Bank,Banking,107095,14%,22126,Mumbai,NaN
34,35,Steel Authority of India,Iron and steel,103861,6%,2372,New Delhi,Yes
35,36,ITC Limited,Consumer goods,93705,31%,34747,Kolkata,NaN
36,37,Wipro,Infotech,92937,1%,13135,Bangalore,NaN
37,38,Flipkart,E-commerce,84230,18%,"−5,189",Bangalore,NaN
38,39,IndiGo,Airline,84098,18%,7258,Gurgaon,NaN
39,40,Bank of India,Banking,80625,19%,9548,Mumbai,Yes
40,41,Indian Bank,Banking,72051,12%,11261,Chennai,Yes
41,42,Hyundai Motor India,Automotive,70282,2%,5640,Gurgaon,NaN
42,43,Tata Power,Utilities,68892,6%,3971,Mumbai,NaN
43,44,Titan Company,Gems and jewellery,68758,27%,3337,Bangalore,NaN
44,45,Toyota Kirloskar Motor,Automotive,65958,16%,5672,Bidadi,NaN
45,46,Hindustan Unilever,Consumer goods,64891,3%,10649,Mumbai,NaN
46,47,Adani Enterprises,Trading,62652,12%,7112,Ahmedabad,NaN
47,48,AWL Agri Business,Consumer goods,61387,24%,1226,Ahmedabad,NaN
48,49,Avenue Supermarts,Retail,60599,17%,2708,Mumbai,NaN
49,50,NABARD,Finance,59292,20%,7803,Mumbai,Yes

In [25]:
url = "https://en.wikipedia.org/wiki/List_of_Indian_IT_companies"

headers = {
    "User-Agent": "MyDataAnalysisBot/1.0 (your_email@example.com)"
}

response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, 'html.parser')

# Step 1: Use find_all to get a list of all matching tables
all_tables = soup.find_all('table', class_='wikitable sortable')
# Step 2: Create a list to store your DataFrames
dfs = []
# Step 3: Loop through each table found for table in all_tables:
for table in all_tables:
# Use StringIO to wrap the string version of the table
    df = pd.read_html(StringIO(str(table)))[0]
    dfs.append(df)

df = pd.read_html(StringIO(str(table)))[0]

pd.set_option('display.max_rows', 100)
print(df)

                                  Name                           Headquarters  \
0                          3i Infotech                                 Mumbai
1                          3i Infotech                                 Mumbai
2                          3i Infotech                                 Mumbai
3                          3i Infotech                                 Mumbai
4            NTT Data Payment Services                                 Mumbai
5                                C-DAC                                   Pune
6                                C-DAC                                   Pune
7                                C-DAC                                   Pune
8                              Coforge            Noida India, New Jersey USA
9                              Coforge            Noida India, New Jersey USA
10                             Coforge            Noida India, New Jersey USA
11                             Coforge            Noida India, New Jersey USA
12                             Coforge            Noida India, New Jersey USA
13                             Coforge            Noida India, New Jersey USA
14                             Coforge            Noida India, New Jersey USA
15                             Coforge            Noida India, New Jersey USA
16                             Coforge            Noida India, New Jersey USA
17                             Coforge            Noida India, New Jersey USA
18                             Coforge            Noida India, New Jersey USA
19                           Cognizant                    Teaneck, New Jersey
20                           Cognizant                    Teaneck, New Jersey
21                           Cognizant                    Teaneck, New Jersey
22                           Cognizant                    Teaneck, New Jersey
23                           Cognizant                    Teaneck, New Jersey
24                           Cognizant                    Teaneck, New Jersey
25                           Cognizant                    Teaneck, New Jersey
26                           Cognizant                    Teaneck, New Jersey
27                           Cognizant                    Teaneck, New Jersey
28                           Cognizant                    Teaneck, New Jersey
29                           Collabera  Morristown, New Jersey, United States
30                           Collabera  Morristown, New Jersey, United States
31                           Collabera  Morristown, New Jersey, United States
32                           Collabera  Morristown, New Jersey, United States
33                           Collabera  Morristown, New Jersey, United States
34                           Collabera  Morristown, New Jersey, United States
35                      DXC Technology                      Ashburn, Virginia
36                              Cyient                              Hyderabad
37                              Cyient                              Hyderabad
38                         Firstsource                                 Mumbai
39                         Firstsource                                 Mumbai
40                     Godrej Infotech                                 Mumbai
41                           Honeywell              Morris Plains, New Jersey
42               HSBC Technology India                                   Pune
43                   KPIT Technologies                                   Pune
44                   KPIT Technologies                                   Pune
45                   KPIT Technologies                                   Pune
46                   KPIT Technologies                                   Pune
47                   KPIT Technologies                                   Pune
48                   KPIT Technologies                                   Pune
49                  Lumen Technologies                          Bengaluru[11]
50                  Lumen Technologies                          Bengaluru[11]
51                  Lumen Technologies                          Bengaluru[11]
52                  Lumen Technologies                          Bengaluru[11]
53                           Microland                              Bangalore
54                           Microsoft                              Hyderabad
55                           Microsoft                              Hyderabad
56                           Microsoft                              Hyderabad
57                           Microsoft                              Hyderabad
58                           Microsoft                              Hyderabad
59                           Microsoft                              Hyderabad
60                           Microsoft                              Hyderabad
61                           Microsoft                              Hyderabad
62                           Microsoft                              Hyderabad
63            Nucleus Software Exports                                  Noida
64                  Persistent Systems                                   Pune
65                  Persistent Systems                                   Pune
66                  Persistent Systems                                   Pune
67                  Persistent Systems                                   Pune
68                  Persistent Systems                                   Pune
69                       Ramco Systems                                Chennai
70                       Ramco Systems                                Chennai
71                          Rediff.com                                 Mumbai
72       Samsung India Software Centre                                  Noida
73                 Sasken Technologies                              Bangalore
74                 Sasken Technologies                              Bangalore
75                 Sasken Technologies                              Bangalore
76                     Sonata Software                              Bangalore
77                     Sonata Software                              Bangalore
78                          EVRY India                              Bangalore
79            Tata Interactive Systems                                 Mumbai
80            Tata Interactive Systems                                Chennai
81            Tata Interactive Systems                                  Kochi
82            Tata Interactive Systems                     Thiruvananthapuram
83            Tata Interactive Systems                              Hyderabad
84            Tata Interactive Systems                                   Pune
85                 WNS Global Services                                 Mumbai
86                 WNS Global Services                                 Mumbai
87                 Zensar Technologies                                   Pune
88                 Zensar Technologies                                   Pune
89                 Zensar Technologies                                   Pune
90                 Zensar Technologies                                   Pune
91                     Tally Solutions                              Bangalore
92                    Zoho Corporation                                Chennai
93  Kellton Tech Solutions Limited[13]                              Hyderabad
94  Kellton Tech Solutions Limited[13]                              Hyderabad

                  City
0            Bengaluru
1            Hyderabad
2               Mumbai
3                Noida
4               Mumbai
5              Kolkata
6                 Pune
7   Thiruvananthapuram
8            New Delhi
9        Greater Noida
10             Kolkata
11             Gurgaon
12              Mumbai
13           Hyderabad
14           Telangana
15           Karnataka
16           Bengaluru
17                Pune
18            Kolhapur
19           Bengaluru
20             Chennai
21       Coimbatore[9]
22             Gurgaon
23           Hyderabad
24               Kochi
25             Kolkata
26       Mangalore[10]
27              Mumbai
28                Pune
29           Bengaluru
30             Gurgaon
31           Hyderabad
32              Mumbai
33             Kolkata
34                Pune
35             Chennai
36           Bengaluru
37           Hyderabad
38         Bhubaneswar
39             Kolkata
40              Mumbai
41             Madurai
42                Pune
43                Pune
44             Chennai
45           Bengaluru
46               Kochi
47              Mumbai
48               Noida
49           Bengaluru
50             Chennai
51           Hyderabad
52               Noida
53           Bengaluru
54           Ahmedabad
55           Bangalore
56             Chennai
57             Gurgaon
58           Hyderabad
59               Kochi
60             Kolkata
61              Mumbai
62           New Delhi
63               Noida
64           Bengaluru
65                 Goa
66           Hyderabad
67              Nagpur
68                Pune
69             Chennai
70              Mumbai
71              Mumbai
72               Noida
73           Bengaluru
74             Chennai
75                Pune
76           Bengaluru
77          Mumbai[12]
78           Bangalore
79              Mumbai
80                 NaN
81                 NaN
82                 NaN
83                 NaN
84                 NaN
85              Mumbai
86              Nashik
87           Hyderabad
88           Bengaluru
89              Mumbai
90                Pune
91           Bangalore
92             Chennai
93             Gurgaon
94             Lucknow

In [27]:
dfs[0]

,Name,Headquarters,Total income,Headcount,City
0,Tata Consultancy Services,Mumbai,"₹ 2,59,282 cr US$31 B (FY'25)","607,979 (FY'25)",Ahmedabad
1,Tata Consultancy Services,Mumbai,"₹ 2,59,282 cr US$31 B (FY'25)","607,979 (FY'25)",Bengaluru
2,Tata Consultancy Services,Mumbai,"₹ 2,59,282 cr US$31 B (FY'25)","607,979 (FY'25)",Bhubaneswar
3,Tata Consultancy Services,Mumbai,"₹ 2,59,282 cr US$31 B (FY'25)","607,979 (FY'25)",Chennai
4,Tata Consultancy Services,Mumbai,"₹ 2,59,282 cr US$31 B (FY'25)","607,979 (FY'25)",Coimbatore
...,...,...,...,...,...
100,Mphasis,Bangalore,"₹ 14,484 cr US$1.7 B (FY'25)","33,771 (FY'23)",Chennai
101,Mphasis,Bangalore,"₹ 14,484 cr US$1.7 B (FY'25)","33,771 (FY'23)",Mangalore
102,Mphasis,Bangalore,"₹ 14,484 cr US$1.7 B (FY'25)","33,771 (FY'23)",Mumbai
103,Mphasis,Bangalore,"₹ 14,484 cr US$1.7 B (FY'25)","33,771 (FY'23)",Pune
104,NaN,NaN,NaN,NaN,NaN

In [ ]:
dfs[1]

,Name,Headquarters,City
0,3i Infotech,Mumbai,Bengaluru
1,3i Infotech,Mumbai,Hyderabad
2,3i Infotech,Mumbai,Mumbai
3,3i Infotech,Mumbai,Noida
4,NTT Data Payment Services,Mumbai,Mumbai
5,C-DAC,Pune,Kolkata
6,C-DAC,Pune,Pune
7,C-DAC,Pune,Thiruvananthapuram
8,Coforge,"Noida India, New Jersey USA",New Delhi
9,Coforge,"Noida India, New Jersey USA",Greater Noida
10,Coforge,"Noida India, New Jersey USA",Kolkata
11,Coforge,"Noida India, New Jersey USA",Gurgaon
12,Coforge,"Noida India, New Jersey USA",Mumbai
13,Coforge,"Noida India, New Jersey USA",Hyderabad
14,Coforge,"Noida India, New Jersey USA",Telangana
15,Coforge,"Noida India, New Jersey USA",Karnataka
16,Coforge,"Noida India, New Jersey USA",Bengaluru
17,Coforge,"Noida India, New Jersey USA",Pune
18,Coforge,"Noida India, New Jersey USA",Kolhapur
19,Cognizant,"Teaneck, New Jersey",Bengaluru
20,Cognizant,"Teaneck, New Jersey",Chennai
21,Cognizant,"Teaneck, New Jersey",Coimbatore[9]
22,Cognizant,"Teaneck, New Jersey",Gurgaon
23,Cognizant,"Teaneck, New Jersey",Hyderabad
24,Cognizant,"Teaneck, New Jersey",Kochi
25,Cognizant,"Teaneck, New Jersey",Kolkata
26,Cognizant,"Teaneck, New Jersey",Mangalore[10]
27,Cognizant,"Teaneck, New Jersey",Mumbai
28,Cognizant,"Teaneck, New Jersey",Pune
29,Collabera,"Morristown, New Jersey, United States",Bengaluru
30,Collabera,"Morristown, New Jersey, United States",Gurgaon
31,Collabera,"Morristown, New Jersey, United States",Hyderabad
32,Collabera,"Morristown, New Jersey, United States",Mumbai
33,Collabera,"Morristown, New Jersey, United States",Kolkata
34,Collabera,"Morristown, New Jersey, United States",Pune
35,DXC Technology,"Ashburn, Virginia",Chennai
36,Cyient,Hyderabad,Bengaluru
37,Cyient,Hyderabad,Hyderabad
38,Firstsource,Mumbai,Bhubaneswar
39,Firstsource,Mumbai,Kolkata
40,Godrej Infotech,Mumbai,Mumbai
41,Honeywell,"Morris Plains, New Jersey",Madurai
42,HSBC Technology India,Pune,Pune
43,KPIT Technologies,Pune,Pune
44,KPIT Technologies,Pune,Chennai
45,KPIT Technologies,Pune,Bengaluru
46,KPIT Technologies,Pune,Kochi
47,KPIT Technologies,Pune,Mumbai
48,KPIT Technologies,Pune,Noida
49,Lumen Technologies,Bengaluru[11],Bengaluru
50,Lumen Technologies,Bengaluru[11],Chennai
51,Lumen Technologies,Bengaluru[11],Hyderabad
52,Lumen Technologies,Bengaluru[11],Noida
53,Microland,Bangalore,Bengaluru
54,Microsoft,Hyderabad,Ahmedabad
55,Microsoft,Hyderabad,Bangalore
56,Microsoft,Hyderabad,Chennai
57,Microsoft,Hyderabad,Gurgaon
58,Microsoft,Hyderabad,Hyderabad
59,Microsoft,Hyderabad,Kochi
60,Microsoft,Hyderabad,Kolkata
61,Microsoft,Hyderabad,Mumbai
62,Microsoft,Hyderabad,New Delhi
63,Nucleus Software Exports,Noida,Noida
64,Persistent Systems,Pune,Bengaluru
65,Persistent Systems,Pune,Goa
66,Persistent Systems,Pune,Hyderabad
67,Persistent Systems,Pune,Nagpur
68,Persistent Systems,Pune,Pune
69,Ramco Systems,Chennai,Chennai
70,Ramco Systems,Chennai,Mumbai
71,Rediff.com,Mumbai,Mumbai
72,Samsung India Software Centre,Noida,Noida
73,Sasken Technologies,Bangalore,Bengaluru
74,Sasken Technologies,Bangalore,Chennai
75,Sasken Technologies,Bangalore,Pune
76,Sonata Software,Bangalore,Bengaluru
77,Sonata Software,Bangalore,Mumbai[12]
78,EVRY India,Bangalore,Bangalore
79,Tata Interactive Systems,Mumbai,Mumbai
80,Tata Interactive Systems,Chennai,NaN
81,Tata Interactive Systems,Kochi,NaN
82,Tata Interactive Systems,Thiruvananthapuram,NaN
83,Tata Interactive Systems,Hyderabad,NaN
84,Tata Interactive Systems,Pune,NaN
85,WNS Global Services,Mumbai,Mumbai
86,WNS Global Services,Mumbai,Nashik
87,Zensar Technologies,Pune,Hyderabad
88,Zensar Technologies,Pune,Bengaluru
89,Zensar Technologies,Pune,Mumbai
90,Zensar Technologies,Pune,Pune
91,Tally Solutions,Bangalore,Bangalore
92,Zoho Corporation,Chennai,Chennai
93,Kellton Tech Solutions Limited[13],Hyderabad,Gurgaon
94,Kellton Tech Solutions Limited[13],Hyderabad,Lucknow